-- A least-privilege database role for local development.
--
-- WHY. Until now relay had exactly one credential and it was root. The IAM user
-- `relay-runtime` held BOTH dsql:DbConnect and dsql:DbConnectAdmin, and
-- lib/db/connection.ts minted `getDbConnectAdminAuthToken()` — so the live
-- production app connected as `admin` with full DDL rights, and the same access
-- key sat in .env.local on a laptop. Nothing anywhere could tell the deployed
-- product apart from a developer's machine, because at the AWS layer they were
-- the same principal.
--
-- Steve's ruling (2026-08-15): only he, acting as a sysadmin, should be able to
-- write to the database outside the product's own features and APIs. There is
-- one cluster and there will be one cluster until G1 is decided, so this is
-- achieved with identity and privilege rather than with environments.
--
-- This file creates the FIRST of the two non-admin roles — the laptop's. The
-- production role (`relay_app`) is a separate, later step, deliberately, so
-- that nothing in this file can affect what is serving customers.
--
--     npx tsx --env-file=.env.local db/migrations/migrate.ts 030_relay_dev_role.sql
--
-- Applied as `admin`; creating roles is itself an admin act, which is the point.
--
-- 🔴 WHY caregiver_leads IS REVOKED, AND WHY THAT IS THE INTERESTING LINE.
-- PROJECT.yaml calls that table "the input to the G1 gate — the measurement
-- that decides whether the product has a market", and the entire worth of that
-- number is that it is ARMS-LENGTH. A lead generated by the team is not weak
-- evidence, it is the opposite of the thing being measured. Because .env.local
-- carries the production Resend key and points at the production cluster,
-- submitting the landing form on a laptop wrote a real row and emailed a real
-- notification, indistinguishable from demand.
--
-- Marking that notification (shipped 2026-08-15) makes a human able to tell.
-- This makes the database refuse. Structural safety over convention, which is
-- the portfolio rule: prefer a structure where the mistake is IMPOSSIBLE over
-- one where every future contributor has to remember.
--
-- DELETE is revoked alongside INSERT and UPDATE. A laptop quietly destroying
-- real leads is strictly worse than one inventing fake ones, and it would be
-- just as invisible.
--
-- SELECT is retained: reading the table is how the app renders and how anybody
-- debugs. Refusing reads would buy nothing and break local development.
--
-- ⚠️ A REFUSAL MUST BE VISIBLE OR THIS WALL IS DECORATION. Before this file was
-- written, the capture route returned `{ok:true}` whenever the notification
-- email succeeded, so a denied INSERT would have looked exactly like a healthy
-- one. That was fixed first, on purpose — SQLSTATE 42501 is now separated from
-- transient failures and answered with 500/CaptureRefused. Do not re-soften it.
--
-- NO DDL IS GRANTED. This role cannot CREATE, ALTER or DROP anything. Migrations
-- stay an explicitly admin act, performed by a sysadmin identity, which is the
-- separation being asked for.
--
-- DSQL: roles are created WITH LOGIN and bound to an IAM principal by
-- `AWS IAM GRANT`. A token minted with dsql:DbConnect can only ever authenticate
-- as a custom role — it cannot become `admin` even if the client asks for it.
-- That is what makes this a wall rather than a policy.
--
-- ROLLBACK: this file is additive and nothing uses the role until
-- lib/db/connection.ts is pointed at it via DSQL_ROLE. To undo:
--   AWS IAM REVOKE relay_dev FROM 'arn:aws:iam::461293170793:user/relay-dev';
--   DROP ROLE relay_dev;
--
-- Requirements: least-privilege ruling 2026-08-15

CREATE ROLE relay_dev WITH LOGIN;

AWS IAM GRANT relay_dev TO 'arn:aws:iam::461293170793:user/relay-dev';

-- ⚠️ NO `GRANT USAGE ON SCHEMA public` HERE, and it is not an oversight.
-- DSQL rejects it: `feature not supported on system entity` (SQLSTATE 0A000).
-- `public` is a system entity on DSQL and its usage is not grantable. The AWS
-- documentation's example grants USAGE on `myschema` — a schema the reader
-- created — which is why copying that example verbatim fails here. Table
-- privileges below work normally; only the schema-level grant is refused.

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO relay_dev;

REVOKE INSERT, UPDATE, DELETE ON caregiver_leads FROM relay_dev;
