-- 033 — the production runtime role. Phase 3 of the least-privilege split.
--
-- 🔴 WHAT IS TRUE UNTIL THE ENV VAR IS SET: THE LIVE SITE IS A DATABASE
-- SUPERUSER. `relay-runtime-policy` grants the production IAM user BOTH
-- `dsql:DbConnect` AND `dsql:DbConnectAdmin` on both cluster ARNs (read from the
-- live policy 2026-08-16, not assumed), and `lib/db/connection.ts` mints
-- `getDbConnectAdminAuthToken()` whenever `DSQL_ROLE` is unset — which it is in
-- production. So every request served by relaystandby.com runs against DSQL as
-- `admin`, with authority to CREATE, ALTER and DROP every table in the product.
--
-- Nothing in the application wants that. It reads and writes rows; it has never
-- issued DDL and migrations are deliberately an admin act performed from a
-- sysadmin identity (see 030). The rights are simply there, unused, waiting for
-- an injection bug or a leaked key to make them matter. This role is the one the
-- app actually needs.
--
-- 030 created the LAPTOP's role and said the production one was "a separate,
-- later step, deliberately, so that nothing in this file can affect what is
-- serving customers". This is that step, and it keeps the same property: it is
-- additive, and it changes nothing until `DSQL_ROLE=relay_app` is set in Vercel.
--
--     npx tsx --env-file=.env.admin db/migrations/migrate.ts 033_relay_app_role.sql
--     DSQL_USE_SECONDARY=true npx tsx --env-file=.env.admin db/migrations/migrate.ts 033_relay_app_role.sql
--
-- ── THE ONE WAY IT DIFFERS FROM relay_dev, AND WHY ──────────────────────────
-- `caregiver_leads` is WRITABLE here. 030 revokes it for the laptop because a
-- lead generated by the team is not weak evidence of demand, it is the opposite
-- of the thing being measured — and `.env.local` points at production, so a form
-- submitted while developing wrote a row indistinguishable from a real one.
--
-- The live site is the exact case that reasoning protects. A lead captured by
-- relaystandby.com from a stranger IS the G1 measurement. Refusing it here would
-- not be caution; it would break the one number the product is being judged on.
-- The distinction the split exists to draw is laptop-versus-production, and this
-- line is where that distinction is actually made.
--
-- ── NO DDL, AND THAT IS THE POINT ───────────────────────────────────────────
-- Only table privileges are granted. CREATE/ALTER/DROP are never given, so a
-- SQL-injection reaching this connection cannot reshape the schema, and a leaked
-- runtime key cannot either. Phase 4 removes `dsql:DbConnectAdmin` from the IAM
-- policy, which closes the remaining door: today an operator who unset
-- `DSQL_ROLE` would silently be admin again, and after phase 4 that is not
-- possible even by mistake.
--
-- ── ALTER DEFAULT PRIVILEGES IS NOT OPTIONAL HERE ───────────────────────────
-- 030 granted `ON ALL TABLES`, which resolves ONCE against the tables existing
-- at that moment. 031 created a table the next day and the first read as
-- relay_dev failed with `permission denied`; 032 fixed the cause. That was an
-- inconvenience on a laptop. The identical omission on THIS role is a production
-- outage on the next migration — every request touching the new table fails,
-- with nothing in the schema check to warn first. So the standing rule is set at
-- the same time as the role, not afterwards.
--
-- ── ROLLBACK ────────────────────────────────────────────────────────────────
-- Cutover is one Vercel environment variable (`DSQL_ROLE=relay_app`) and
-- rollback is removing it — the app returns to the admin path on the next
-- deployment. Nothing here has to be undone for that. To remove the role itself:
--   ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM relay_app;
--   REVOKE ALL ON ALL TABLES IN SCHEMA public FROM relay_app;
--   AWS IAM REVOKE relay_app FROM 'arn:aws:iam::461293170793:user/relay-runtime';
--   DROP ROLE relay_app;
--
-- Requirements: least-privilege ruling 2026-08-15, phase 3

CREATE ROLE relay_app WITH LOGIN;

-- The principal production ALREADY uses. Read from relay-runtime-policy rather
-- than assumed: binding this to the wrong user would produce a role nothing can
-- authenticate as, and the failure would appear only at cutover.
AWS IAM GRANT relay_app TO 'arn:aws:iam::461293170793:user/relay-runtime';

-- No `GRANT USAGE ON SCHEMA public` — DSQL refuses it (`feature not supported on
-- system entity`, SQLSTATE 0A000). See 030's note; table privileges work.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO relay_app;

-- Everything created from here on, so migration N+1 cannot lock production out.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO relay_app;
