/**
 * scripts/verify-roles.ts — is the least-privilege split still what it claims?
 * Both regions, read-only.
 *
 *   npm run verify:roles         (runs as `relay_ro` via --env-file=.env.ro)
 *
 * ⚠️ This line read `--env-file=.env.local` until 2026-08-29 (H stale-description
 * list) while `package.json` has run it on `.env.ro` since 2026-08-21. That is the
 * expensive direction to be stale in: CLAUDE.md's own lesson is that **a stale
 * warning costs more than a stale claim, because it is obeyed** — this one told an
 * operator to reach for the credential that can WRITE in order to run a read-only
 * check. Derive the truth rather than trusting any header:
 *   node -e "const p=require('./package.json');console.log(p.scripts['verify:roles'])"
 *
 * WHY THIS EXISTS. The split is enforced by GRANTs on a live cluster, and a
 * GRANT leaves no trace in this repository. `db/migrations/*.sql` records what
 * was INTENDED at the moment each file ran; it cannot tell you what is true now.
 * Anyone with admin can widen a role in one statement, `ALTER DEFAULT
 * PRIVILEGES` silently changes what future tables inherit, and neither shows up
 * in a diff, a test run or a build.
 *
 * That matters more here than for most schema facts, because the whole point of
 * the split is a wall: production may not issue DDL, and a laptop may not write
 * the G1 measurement table. A wall nobody re-measures is a wall until the day it
 * is not, and this repo's recurring defect is a green signal that stopped
 * meaning anything.
 *
 * 🔴 IT ALSO CATCHES THE OMISSION THAT ALREADY HAPPENED. Migration 030 granted
 * `ON ALL TABLES`, which resolves ONCE against the tables existing then. 031
 * created one the next day and the first read as relay_dev failed with
 * `permission denied`. That was an inconvenience on a laptop; the identical
 * omission on `relay_app` is a production outage on the next migration — every
 * request touching the new table fails. 032/033 set default privileges so the
 * rule covers tables that do not exist yet, and this asserts the result rather
 * than trusting that they ran.
 *
 * BOTH REGIONS, for the reason verify:schema gives: failover is an env switch
 * (`DSQL_USE_SECONDARY`), so a grant applied to one region and not the other is
 * invisible until the day somebody flips it.
 *
 * READ-ONLY BY CONSTRUCTION. Only SELECTs against `pg_roles`,
 * `sys.iam_pg_role_mappings` and the `has_*_privilege` functions. It creates
 * nothing and grants nothing, so it is safe against production — which is the
 * only place worth running it.
 *
 * NOT IN CI, for the reason verify:schema is not: CI holds no cluster
 * credentials. Run it after any migration, and before and after a role cutover.
 *
 * Feature: least-privilege ruling 2026-08-15
 */

import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';

import { Client } from 'pg';
import { DsqlSigner } from '@aws-sdk/dsql-signer';

import { declaredTables } from '../lib/db/schema-manifest';
import { dsqlIdentity } from '../lib/db/connection';

const MIGRATIONS_DIR = path.resolve(__dirname, '..', 'db', 'migrations');

/**
 * THE CONTRACT, written once, here.
 *
 * `writesEverything` is the difference the whole split turns on, and it is worth
 * stating rather than leaving implicit in a REVOKE buried in migration 030:
 *
 *   relay_app  — the LIVE SITE. Writes `caregiver_leads`, because a lead
 *                captured from a stranger IS the G1 measurement.
 *   relay_dev  — a LAPTOP. Reads it and cannot write it, because a lead
 *                generated by the team is not weak evidence of demand, it is the
 *                opposite of the thing being measured, and `.env.local` points
 *                at production.
 *
 * Neither may hold DDL. Migrations are an admin act performed from a sysadmin
 * identity, which is the separation being asked for.
 */
const MEASUREMENT_TABLE = 'caregiver_leads';

interface RoleContract {
  role: string;
  iamArn: string;
  /** May this role write the G1 measurement table? */
  writesMeasurementTable: boolean;
  /**
   * Does this role hold write DML on ANY table?
   *
   * Optional and defaulting to `true`, so the two roles this file was written
   * for are unchanged. It exists for `relay_ro`, added 2026-08-21, which holds
   * SELECT and nothing else — and which this checker would otherwise have
   * ignored entirely.
   *
   * ⚠️ THAT WOULD HAVE BEEN THE FAMILIAR FAILURE. This file's own header says
   * why it exists: the least-privilege split is enforced by GRANTs on a live
   * cluster, and "anyone with admin can widen a role in one statement that
   * appears in no diff, test run or build". A new wall that this instrument does
   * not watch is a wall that can be widened silently — so a read-only role that
   * quietly acquired INSERT would look exactly like a read-only role.
   */
  writesAnything?: boolean;
}

const CONTRACT: RoleContract[] = [
  {
    role: 'relay_app',
    iamArn: 'arn:aws:iam::461293170793:user/relay-runtime',
    writesMeasurementTable: true,
  },
  {
    role: 'relay_dev',
    iamArn: 'arn:aws:iam::461293170793:user/relay-dev',
    writesMeasurementTable: false,
  },
  {
    /*
      The verification identity (migration 039). Reads everything, writes
      nothing, and its IAM policy carries `dsql:DbConnect` and NO KMS — so it can
      read metadata and can never turn a ciphertext column into a secret.
      It exists so that an agent running somewhere other than this laptop can
      check the live system at all: verify:schema, verify:dogfood,
      verify:orphans, flight:snapshot and this file all need only SELECT.
    */
    role: 'relay_ro',
    iamArn: 'arn:aws:iam::461293170793:user/relay-ro',
    writesMeasurementTable: false,
    writesAnything: false,
  },
];

const DML = ['SELECT', 'INSERT', 'UPDATE', 'DELETE'] as const;

interface Target {
  label: string;
  endpoint: string | undefined;
}

async function connect(endpoint: string): Promise<Client> {
  const match = endpoint.match(/\.dsql\.([a-z0-9-]+)\.on\.aws$/i);
  const region = match ? match[1] : (process.env.AWS_REGION ?? 'us-east-1');
  const signer = new DsqlSigner({ hostname: endpoint, region });
  const { user, admin } = dsqlIdentity();

  const client = new Client({
    host: endpoint,
    port: parseInt(process.env.DSQL_PORT ?? '5432', 10),
    database: process.env.DSQL_DATABASE ?? 'postgres',
    user,
    password: () => (admin ? signer.getDbConnectAdminAuthToken() : signer.getDbConnectAuthToken()),
    ssl: { rejectUnauthorized: process.env.DSQL_SSL_REJECT_UNAUTHORIZED !== 'false' },
    connectionTimeoutMillis: 10_000,
    query_timeout: 30_000,
  });
  await client.connect();
  return client;
}

/** Every problem found in one region. Empty means the wall is where it says. */
async function auditRegion(client: Client, tables: string[]): Promise<string[]> {
  const problems: string[] = [];

  // ── The roles exist and hold no role-level power ──────────────────────────
  const roles = await client.query<{
    rolname: string;
    rolsuper: boolean;
    rolcreatedb: boolean;
    rolcreaterole: boolean;
    rolcanlogin: boolean;
  }>(
    `SELECT rolname, rolsuper, rolcreatedb, rolcreaterole, rolcanlogin
       FROM pg_roles WHERE rolname = ANY($1)`,
    [CONTRACT.map((c) => c.role)],
  );
  const byName = new Map(roles.rows.map((r) => [r.rolname, r]));

  for (const c of CONTRACT) {
    const r = byName.get(c.role);
    if (!r) {
      problems.push(`role ${c.role} DOES NOT EXIST`);
      continue;
    }
    if (!r.rolcanlogin) problems.push(`${c.role} cannot log in`);
    // Role-level power is a second door to the same room: CREATEROLE can grant
    // itself anything, so it is checked even though the DDL check below exists.
    if (r.rolsuper) problems.push(`${c.role} is SUPERUSER`);
    if (r.rolcreatedb) problems.push(`${c.role} has CREATEDB`);
    if (r.rolcreaterole) problems.push(`${c.role} has CREATEROLE`);
  }

  // ── No DDL: it cannot create objects in the database or the schema ────────
  for (const c of CONTRACT) {
    if (!byName.has(c.role)) continue;
    const d = await client.query<{ db: boolean; sch: boolean }>(
      `SELECT has_database_privilege($1, current_database(), 'CREATE') AS db,
              has_schema_privilege($1, 'public', 'CREATE') AS sch`,
      [c.role],
    );
    if (d.rows[0].db) problems.push(`${c.role} may CREATE in the database — DDL is an admin act`);
    if (d.rows[0].sch) problems.push(`${c.role} may CREATE in schema public — DDL is an admin act`);
  }

  // ── The IAM binding is what we think it is ────────────────────────────────
  //
  // Checked against the cluster's own catalogue rather than inferred from the
  // migration that ran. A role bound to the wrong principal is a role nothing
  // can authenticate as, and that failure would surface only at cutover — on
  // production, under load, with no obvious cause.
  const maps = await client.query<{ arn: string; pg_role_name: string }>(
    `SELECT arn, pg_role_name FROM sys.iam_pg_role_mappings WHERE pg_role_name = ANY($1)`,
    [CONTRACT.map((c) => c.role)],
  );
  for (const c of CONTRACT) {
    const bound = maps.rows.filter((m) => m.pg_role_name === c.role).map((m) => m.arn);
    if (!bound.includes(c.iamArn)) {
      problems.push(
        `${c.role} is not bound to ${c.iamArn} (bound to: ${bound.length ? bound.join(', ') : 'nothing'})`,
      );
    }
    const extra = bound.filter((a) => a !== c.iamArn);
    // A second principal on a role is how a wall quietly acquires a side door.
    if (extra.length) problems.push(`${c.role} has EXTRA IAM principals: ${extra.join(', ')}`);
  }

  // ── Table privileges, every declared table, both roles ────────────────────
  for (const c of CONTRACT) {
    if (!byName.has(c.role)) continue;
    for (const t of tables) {
      // `writesAnything === false` short-circuits every write verb on every
      // table: a read-only role has no per-table exceptions to make.
      const wantWrite =
        c.writesAnything === false
          ? false
          : t === MEASUREMENT_TABLE
            ? c.writesMeasurementTable
            : true;
      for (const priv of DML) {
        const want = priv === 'SELECT' ? true : wantWrite;
        const got = await client.query<{ ok: boolean }>(
          `SELECT has_table_privilege($1, $2, $3) AS ok`,
          [c.role, t, priv],
        );
        if (got.rows[0].ok !== want) {
          problems.push(
            want
              ? `${c.role} LACKS ${priv} on ${t} — the application cannot do its job`
              : `${c.role} HAS ${priv} on ${t} — the wall is open`,
          );
        }
      }
    }
  }

  return problems;
}

async function main(): Promise<void> {
  const files = readdirSync(MIGRATIONS_DIR).filter((f) => f.endsWith('.sql'));
  const tables = declaredTables(files.map((f) => readFileSync(path.join(MIGRATIONS_DIR, f), 'utf8')));

  console.log(
    `[roles] checking ${CONTRACT.length} role(s) against ${tables.length} declared tables, as ${dsqlIdentity().user}.`,
  );

  const targets: Target[] = [
    { label: 'primary   (us-east-1)', endpoint: process.env.DSQL_PRIMARY_ENDPOINT },
    { label: 'secondary (us-west-2)', endpoint: process.env.DSQL_SECONDARY_ENDPOINT },
  ];

  let failed = false;
  let checked = 0;

  for (const { label, endpoint } of targets) {
    if (!endpoint) {
      // Stated, never skipped silently — a region not checked must not read as
      // a region that passed.
      console.log(`[roles] ${label}: SKIPPED — no endpoint configured.`);
      continue;
    }

    let client: Client;
    try {
      client = await connect(endpoint);
    } catch (err) {
      console.error(`[roles] ${label}: UNREACHABLE — ${(err as Error).message}`);
      failed = true;
      continue;
    }

    try {
      const problems = await auditRegion(client, tables);
      checked += 1;
      if (problems.length) {
        console.error(`[roles] ${label}: ✗ ${problems.length} problem(s):`);
        for (const p of problems) console.error(`           - ${p}`);
        failed = true;
      } else {
        console.log(`[roles] ${label}: ✓ the split is intact.`);
      }
    } finally {
      await client.end();
    }
  }

  if (checked === 0) {
    console.error('[roles] FAILED: no region was actually checked.');
    process.exit(1);
  }
  if (failed) {
    console.error('[roles] FAILED — the privilege split is not what the migrations describe.');
    process.exit(1);
  }
  console.log(
    // Derived from CONTRACT rather than spelled out, because this line said
    // "relay_dev cannot; NEITHER holds DDL" while three roles were being
    // checked — a summary that silently stops describing what ran is the
    // smallest version of the drift this whole file exists to catch.
    `[roles] OK — ${checked} region(s). ${CONTRACT.length} roles: ` +
      CONTRACT.map(
        (c) =>
          `${c.role} ${c.writesAnything === false ? 'reads only' : c.writesMeasurementTable ? `writes ${MEASUREMENT_TABLE}` : `cannot write ${MEASUREMENT_TABLE}`}`,
      ).join('; ') +
      '. None holds DDL.',
  );
}

main().catch((err) => {
  console.error('[roles] Unexpected error:', err);
  process.exit(1);
});
